.\" Encoding: iso-8859-1
.
.de IPn
.na
.nh
.IP "\\$1"
.ad
.hy
..
.
.\" ------------------------------------------------------------------
.\" ------------------------------------------------------------------
.\" ------------------------------------------------------------------
.TH "plow" "1" "local" "René Bählkow" "The Playlist Generator"
.\" ------------------------------------------------------------------
.\" ------------------------------------------------------------------
.\" ------------------------------------------------------------------
.SH "NAME"
plow \- create m3u playlist (and start a player)
.\" ------------------------------------------------------------------
.\" ------------------------------------------------------------------
.\" ------------------------------------------------------------------
.SH "SYNOPSIS"
.na
.nh
\fBplow\fR [-|+<c>[e] <str> [<str>]*]* [\-Q] [\-0...9] [\-S] [\-\-add]
[\-\-noplay]
.br
\fBplow\fR [-|+<c>[e] <str> [<str>]*]* [\-Q] \-\-set <c> <str>
[<c> <str>]*
.br
\fBplow\fR \-L <tbl>
.br
\fBplow\fR \-q <sql>
.br
\fBplow\fR \-C
.br
\fBplow\fR \-I \fI/path/to/music\fR
.br
\fBplow\fR \-\-help
.br
\fBplow\fR \-\-version
.ad
.hy
.\" ------------------------------------------------------------------
.\" ------------------------------------------------------------------
.\" ------------------------------------------------------------------
.SH "DESCRIPTION"
\fBplow\fR is a powerfull command\-line tool for putting songs
from your music collection into a playlist. Most id3v2/ogg tag
information is used by \fBplow\fR to create a (sqlite3)
database for filtering. Additionaly \fBplow\fR supports
fields like mood, tempo, language, etc.
.\" ------------------------------------------------------------------
.\" ------------------------------------------------------------------
.\" ------------------------------------------------------------------
.SH "OPTIONS"
.
.IPn "\fB\-|+<c>[e] <str> [<str>]*"
This sets the filter for creating the playlist.
.PD 0
.RS 8
.IPn "\-"
search for fields containing <str>
.IPn "+"
search for fields \fBnot\fR containing <str>
.IPn "e"
<str> matches exactly
.IPn "<c>"
is one of the following characters:
.RS 16
.IPn "A"
album
.IPn "a"
artist
.IPn "g"
genre
.IPn "l"
language
.IPn "m"
mood
.IPn "r"
rating
.IPn "s"
situation
.IPn "t"
tempo
.IPn "T"
title
.RE
.RE
.PD 1
.
.IPn "\fB\-\-set <c> <str> [<c> <str>]*"
This sets the field <c> to <str> in all songs that matches the actual
filter.
.PD 0
.RS 8
.IPn "<c>"
is one of the following characters:
.RS 16
.IPn "A"
album
.IPn "a"
artist
.IPn "g"
genre
.IPn "l"
language
.IPn "m"
mood
.IPn "r"
rating
.IPn "s"
situation
.IPn "t"
tempo
.RE
.RE
.PD 1
.
.IPn "\fB\-Q"
Print out the executed SQL query.
.
.IPn "\fB\-0...9"
Select the player set in configuration file.
.
.IPn "\fB\-S"
Shuffle the playlist.
.
.IPn "\fB\-\-add"
Append the files to the playlist (do not overwrite the old one).
.
.IPn "\fB\-\-noplay"
Create the playlist normally, but do not start a player.
.
.IPn "\fB\-L <tbl>"
Print out values for <tbl>. <tbl> is one of album, artist, genre,
language, mood, rating, situation or tempo.
.
.IPn "\fB\-q <sql>"
Execute SQL query <sql> and print the result.
.
.IPn "\fB\-C"
Copy all files in the current playlist to the portable device
set in configuration file.
.
.IPn "\fB\-I /path/to/music"
Add files in /path/to/music to database. Files allready in database
are ignored.
.
.IPn "\fB\-\-help"
Print out a help message.
.
.IPn "\fB\-\-version"
Print out version.
.\" ------------------------------------------------------------------
.\" ------------------------------------------------------------------
.\" ------------------------------------------------------------------
.SH "EXAMPLES"
.\" ------------------------------------------------------------------
.SS "CREATING PLAYLISTS"
.IPn "plow"
This creates a playlist containing all songs.
.IPn "plow \-a queen"
artist contains queen
.IPn "plow \-a queen \-T rock"
artist contains queen \fBand\fR title
contains rock
.IPn "plow \-ae Queen"
artist is exactly Queen
.IPn "plow +a queen"
artist \fBnot\fR contains queen
.IPn "plow +ae Queen"
artist \fBis not\fR Queen
.IPn "plow \-a queen beatles"
artist contains queen \fBor\fR beatles
.IPn "plow \-a queen +a queens"
artist contains queen \fBand not\fR queens
.IPn "plow \-a queen \-a 'stone age'"
artist contains queen \fBand\fR stone age
.\" ------------------------------------------------------------------
.SS "SETTING VALUES"
.IPn "plow \-a queen \-\-set l english r 'best music ever'"
sets language = english and rating = 'best music ever' for all songs
where artist contains queen
.\" ------------------------------------------------------------------
.\" ------------------------------------------------------------------
.\" ------------------------------------------------------------------
.SH "CONFIGURATION FILE"
\fI~/.plow/plow.conf\fR is the configuration file for plow. It is in
an INI like format with \fB[section]\fR and \fBkey=value\fR pairs.
Lines starting with a \fB#\fR are comments. Whitespaces are ignored,
except in the value.
.\" ------------------------------------------------------------------
.SS "SECTION [general]"
.
.IPn "path = /path/to/music"
If all your music is in one folder you can set it here. If you add
songs to your database path is stripped from file names.
.br
Default: empty
.
.IPn "playlist = /path/to/playlist"
Sets the path to the playlist. The file name is always plow.m3u.
This value is given as an argument to the players you set.
.br
Default: ~/.plow
.
.IPn "order = album ASC, part ASC, track ASC"
Sets the default output order. This is in SQL syntax.
.br
Default: album ASC, part ASC, track ASC
.
.IPn "player0 = mplayer \-playlist"
Here you have to set your default player, so that it plays a playlist.
The playlist is given as an argument to the players.
.br
Default: empty (in default configuration file it is mplayer -playlist)
.
.IPn "player[1..9] = <player-executable -options>"
You can set up to 8 additional player. If one is not found, plow will
fallback to player0.
.br
Default: empty
.
.IPn "playernofork = 0"
If you do not want plow to fork a player, then add its number here
(you can use space or nothing to seperate them). This is normally
the case if you use a command-line player like mplayer.
.br
Default: empty
.
.IPn "portable = /path/to/portable/player"
Sets the path to your portable device.
.br
Default: empty
.

.IPn "portable_name = [artistOrAlbum] / [albumOrEmpty] \- [part0] \- [track0] \- [emptyOrArtist] \- [title] [extension]"
If you want plow to rename the files before copying to portable, you
can set here how to do that. Therefore you can use all fields from the
database surrounded by '[' and ']' like [title]. Additionally there
are some special fields like [artistOrAlbum], which are explained
in "SPECIAL FIELDS FOR portable_name AND extinf" below.
.br
The following characters are replaced by a '_':
\\\\n\\r\\t"'$@*{}[]()/:;&? and space
.br
The fields and strings here are seperated by space characters.
.br
The value above will create something like
.nh
Queen/The_Platinum_Collection-01-16-We_will_rock_you.ogg for a
song from a normal album and something like
The_Matrix/01-07-The_Prodigy-Mindfields.ogg
.hy
for a song from a compilation album.
.br
Default: empty (no renaming)
.
.IPn "etxtinf = [length] "", "" [artist] "" - "" [title]"
A m3u file can contain extended information, so if a player can't
read tags from files  or reads them only if the file is played,
it shows (maybe) this as file information. You can use the same
as in portable_name here.
.br
Default: empty (no extinf in playlist)
.
.IPn "extensions = mp3 MP3 ogg OGG"
If your music folders contains other files than the songs, set here
which extensions your music files have. Otherwise plow tries to
read tags from every file.
.br
Default: empty (no filtering by file extension)
.\" ------------------------------------------------------------------
.SS "SECTION [abbr]"
In this section you can set abbrevations for often used commands.
You can use all command-line options here. An abbrevation is something
like <name> = options. Abbrevations are called with a '.', like
plow .compilation or plow .rock. Examples:
.
.IPn "complilation = -q ""SELECT album FROM tbl_album WHERE  album_id_artist=1;"""
This executes the sql command and prints out a table containing all
albums that are compilations (tbl_album.album_id_artist = 1).
.
.IPn "rock = -g rock -r good best"
This creates a playlist containig all files where genre contains rock
and rating contains good or best.
.\" ------------------------------------------------------------------
.SS "SECTION [vorbis]"
Here you set how your ogg/vorbis files are tagged. (The values here
are the defaults used by plow.)
.IPn "title     = TITLE"
.IPn "artist    = ARTIST"
.IPn "album     = ALBUM"
.IPn "part      = DISCNUMBER"
If you have a record that is divided into more than one disc, this
field is used for the disc number.
.IPn "track     = TRACKNUMBER"
.IPn "genre     = GENRE"
.IPn "comment   = COMMENT"
.IPn "date      = DATE"
.IPn "id        = ID"
This is used for unique file ids.
.IPn "parts     = DISCS"
If you have a record that is divided into more than one disc, this
field is used for the total number of discs.
.IPn "tracks    = TRACKS"
.IPn "rating    = RATING"
.IPn "mood      = MOOD"
.IPn "situation = SITUATION"
.IPn "tempo     = TEMPO"
.IPn "language  = LANGUAGE"
.\"-------------------------------------------------------------------
.SS "SECTION [id3v2]"
Here you set how your mp3s are tagged. Since ID3v2 is more restricted
then vorbis comments you could only change the 'special' fields here.
.br
plow supports the following frame types:
.PD 0
.RS 8
.IPn "TXXX"
user text frame with a description string
.IPn "COMM"
comment frame with a description string and a language
(the language is ignored by plow)
.IPn "UFID"
unique file identifier frame with an owner string
.IPn "POPM"
popularimeter frame (rating) with an owner string
.RE
.PD 1
.PP
The frame identifier have to be followed by a '/' and the description
or owner string you used in the frame. If you just want to use the
first frame of that type, or there is just one, than you can use
a '*'. Is there nothing after the '/' it means an empty description or
owner string.
.PP
You can use all frame types for all fields, e.g. tempo = UFID/* or
rating = COMM/rating.
.PP
(The values here are the defaults used by plow.)
.IPn "id        = UFID/*"
.IPn "comment   = COMM/"
.IPn "rating    = POPM/*"
.IPn "mood      = TXXX/MOOD"
.IPn "situation = TXXX/SITUATION"
.IPn "tempo     = TXXX/TEMPO"
.IPn "language  = TXXX/LANGUAGE"
.\" ------------------------------------------------------------------
.SS "SPECIAL FIELDS FOR portable_name AND extinf"
.IPn "[track0]"
track number with a leading 0
.IPn "[tracks0]"
total number of tracks with a leading 0
.IPn "[part0]"
part number with a leading 0
.IPn "[parts0]"
total number of parts with a leading 0
.IPn "[extension]"
file extension (the part from the last '.' of tbl_music.file)
.IPn "[artistOrEmpty]"
artist if the album is no compilation, empty otherwise
.IPn "[albumOrEmpty]"
album if the album is no compilation, empty otherwise
.IPn "[emptyOrArtist]"
empty if the album is no compilation, artist otherwise
.IPn "[emptyOrAlbum]"
empty if the album is no compilation, album otherwise
.IPn "[artistOrAlbum]"
artist if the album is no compilation, album otherwise
.IPn "[albumOrArtist]"
album if the album is no compilation, artist otherwise
.RE
.\" ------------------------------------------------------------------
.\" ------------------------------------------------------------------
.\" ------------------------------------------------------------------
.SH "DATABASE FILE"
\fI~/.plow/plow.sqlite\fR is a SQLite3 database file containing all
the data used by plow.
.\" ------------------------------------------------------------------
.\" ------------------------------------------------------------------
.\" ------------------------------------------------------------------
.SH "AUTHOR"
René Bählkow
.\" ------------------------------------------------------------------
.\" ------------------------------------------------------------------
.\" ------------------------------------------------------------------
.SH "SEE ALSO"
\fIhttp://plow.projekt182.de/
